on:
  push:
    branches:
      - production

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node
          target-branch: production
          
      - name: Auto-merge release PR
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        run: |
          gh pr merge "${{ fromJson(steps.release.outputs.pr).number }}" \
            --repo "${{ github.repository }}" \
            --squash \
            --delete-branch
